# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Backend-neutral launcher geometry and baseline launcher component models."""

from .atmosphere import DensityDragModel, quadratic_axial_drag_force_n
from .analytic import (
    CartBrakingResult,
    GuidedTrajectoryResult,
    simulate_cart_braking,
    simulate_guided_launch,
)
from .brake import BrakeCommand, ForceLimitedCartBrake, compute_brake_command
from .geometry import (
    BoundaryCrossing,
    BodyClearanceReport,
    CenterlinePose,
    CircularCenterlineSegment,
    ClothoidCenterlineSegment,
    CurvedTubeLayout,
    PlanarCenterline,
    RigidBodyEnvelope,
    TubePath,
    StraightCenterlineSegment,
    SweptEnvelopeReport,
    TubeLayout,
    TubeStage,
    axial_position,
    axial_velocity,
    cumulative_boundaries,
    effective_density_ratio,
    enumerate_boundary_crossings,
    gravity_projection,
    guide_normal_bound_mps2,
    path_pose,
    normal_jerk_mps3,
    refine_density_stages,
    stage_index,
    swept_envelope_clearance,
    tube_axis,
    world_position,
)
from .guide import IdealPathGuide
from .launch_force import (
    AbstractAxialLaunchForce,
    LaunchCommand,
    compute_launch_command,
    guide_resistance_force_n,
    launch_ramp_factor,
)

__all__ = [
    "BoundaryCrossing",
    "BodyClearanceReport",
    "AbstractAxialLaunchForce",
    "BrakeCommand",
    "CartBrakingResult",
    "CenterlinePose",
    "CircularCenterlineSegment",
    "ClothoidCenterlineSegment",
    "CurvedTubeLayout",
    "DensityDragModel",
    "GuidedTrajectoryResult",
    "ForceLimitedCartBrake",
    "IdealPathGuide",
    "LaunchCommand",
    "PlanarCenterline",
    "RigidBodyEnvelope",
    "TubePath",
    "StraightCenterlineSegment",
    "SweptEnvelopeReport",
    "TubeLayout",
    "TubeStage",
    "axial_position",
    "axial_velocity",
    "cumulative_boundaries",
    "compute_launch_command",
    "compute_brake_command",
    "effective_density_ratio",
    "enumerate_boundary_crossings",
    "gravity_projection",
    "guide_normal_bound_mps2",
    "guide_resistance_force_n",
    "launch_ramp_factor",
    "path_pose",
    "normal_jerk_mps3",
    "quadratic_axial_drag_force_n",
    "simulate_guided_launch",
    "simulate_cart_braking",
    "refine_density_stages",
    "stage_index",
    "swept_envelope_clearance",
    "tube_axis",
    "world_position",
]
